name: young_refractometry
description: AI-powered mobile young refractometry app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Camera
  camera: ^0.10.5+5
  
  # Face Detection
  google_mlkit_face_detection: ^0.9.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # UI
  flutter_svg: ^2.0.9
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true